/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fikatugas_19april;

import javax.swing.JOptionPane;

/**
 *
 * @author Vika
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelkalkulator = new javax.swing.JLabel();
        labelangka1 = new javax.swing.JLabel();
        labelangka2 = new javax.swing.JLabel();
        textangkapertama = new javax.swing.JTextField();
        textangkakedua = new javax.swing.JTextField();
        buttontambah = new javax.swing.JButton();
        buttonkali = new javax.swing.JButton();
        buttonkurang = new javax.swing.JButton();
        buttonbagi = new javax.swing.JButton();
        buttondiv = new javax.swing.JButton();
        buttonmod = new javax.swing.JButton();
        labelhasil = new javax.swing.JLabel();
        texthasil = new javax.swing.JTextField();
        buttonreset = new javax.swing.JButton();
        buttonexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelkalkulator.setText("kalkulator");

        labelangka1.setText("angka 1");

        labelangka2.setText("angka 2");

        textangkapertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textangkapertamaActionPerformed(evt);
            }
        });

        buttontambah.setText("+");
        buttontambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontambahActionPerformed(evt);
            }
        });

        buttonkali.setText("*");
        buttonkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkaliActionPerformed(evt);
            }
        });

        buttonkurang.setText("-");
        buttonkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkurangActionPerformed(evt);
            }
        });

        buttonbagi.setText("/");
        buttonbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbagiActionPerformed(evt);
            }
        });

        buttondiv.setText("div");
        buttondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondivActionPerformed(evt);
            }
        });

        buttonmod.setText("mod");
        buttonmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmodActionPerformed(evt);
            }
        });

        labelhasil.setText("hasil");

        buttonreset.setText("reset");
        buttonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonresetActionPerformed(evt);
            }
        });

        buttonexit.setText("exit");
        buttonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(labelkalkulator))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelangka1)
                                .addComponent(labelangka2)
                                .addComponent(labelhasil))
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textangkakedua, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                .addComponent(textangkapertama)
                                .addComponent(texthasil))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonreset)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttontambah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonkali, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonexit, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonmod, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelkalkulator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelangka1)
                    .addComponent(textangkapertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelangka2)
                    .addComponent(textangkakedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelhasil)
                    .addComponent(texthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttontambah)
                    .addComponent(buttonkali)
                    .addComponent(buttonkurang)
                    .addComponent(buttonbagi)
                    .addComponent(buttondiv)
                    .addComponent(buttonmod))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonreset)
                    .addComponent(buttonexit))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttontambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontambahActionPerformed
     int a = Integer.parseInt(textangkapertama.getText());
     int b = Integer.parseInt(textangkakedua.getText());
     int hasil= a+b;
     
     texthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_buttontambahActionPerformed

    private void textangkapertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textangkapertamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textangkapertamaActionPerformed

    private void buttonkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkaliActionPerformed
     int a = Integer.parseInt(textangkapertama.getText());
     int b = Integer.parseInt(textangkakedua.getText());
     int hasil= a*b;
     
     texthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_buttonkaliActionPerformed

    private void buttonkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkurangActionPerformed
     int a = Integer.parseInt(textangkapertama.getText());
     int b = Integer.parseInt(textangkakedua.getText());
     int hasil= a-b;
     
     texthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_buttonkurangActionPerformed

    private void buttonbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbagiActionPerformed
     float a = Integer.parseInt(textangkapertama.getText());
     float b = Integer.parseInt(textangkakedua.getText());
     float hasil= a/b;
     //karna bagi jadi angka berkoma maka pakai float
     
     texthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_buttonbagiActionPerformed

    private void buttondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondivActionPerformed
     int a = Integer.parseInt(textangkapertama.getText());
     int b = Integer.parseInt(textangkakedua.getText());
     int hasil= a / b;
     
     texthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_buttondivActionPerformed

    private void buttonmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmodActionPerformed
     int a = Integer.parseInt(textangkapertama.getText());
     int b = Integer.parseInt(textangkakedua.getText());
     int hasil= a % b; 
    }//GEN-LAST:event_buttonmodActionPerformed

    private void buttonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonresetActionPerformed
        textangkapertama.setText("");
        textangkakedua.setText("");
        texthasil.setText("");
    }//GEN-LAST:event_buttonresetActionPerformed

    private void buttonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonexitActionPerformed
  
        int jawab = JOptionPane.showOptionDialog(this,
                "apakah ingin keluar ?",
                "keluar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,null,null);
        if (jawab==JOptionPane.NO_OPTION)
            System.exit(0);
    }//GEN-LAST:event_buttonexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonbagi;
    private javax.swing.JButton buttondiv;
    private javax.swing.JButton buttonexit;
    private javax.swing.JButton buttonkali;
    private javax.swing.JButton buttonkurang;
    private javax.swing.JButton buttonmod;
    private javax.swing.JButton buttonreset;
    private javax.swing.JButton buttontambah;
    private javax.swing.JLabel labelangka1;
    private javax.swing.JLabel labelangka2;
    private javax.swing.JLabel labelhasil;
    private javax.swing.JLabel labelkalkulator;
    private javax.swing.JTextField textangkakedua;
    private javax.swing.JTextField textangkapertama;
    private javax.swing.JTextField texthasil;
    // End of variables declaration//GEN-END:variables
}
