/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aulia_28maret24;

/**
 *
 * @author Vika
 */
public class FormStudent extends javax.swing.JFrame {

    /**
     * Creates new form FormStudent
     */
    public FormStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUmur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatematika = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBing = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIlmuPengetahuan = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtHasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 140, 20);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(140, 20, 250, 20);

        jLabel2.setText("alamat");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 60, 16);
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(140, 50, 250, 22);

        jLabel3.setText("umur");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 29, 16);
        getContentPane().add(txtUmur);
        txtUmur.setBounds(140, 80, 250, 22);

        jLabel4.setText("matematika");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 70, 16);
        getContentPane().add(txtMatematika);
        txtMatematika.setBounds(140, 110, 250, 22);

        jLabel5.setText("b.inggris");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 50, 16);
        getContentPane().add(txtBing);
        txtBing.setBounds(140, 140, 250, 22);

        jLabel6.setText("ilmu pengetahuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 100, 16);
        getContentPane().add(txtIlmuPengetahuan);
        txtIlmuPengetahuan.setBounds(140, 170, 250, 22);

        btnProses.setText("btnproses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(10, 200, 90, 23);

        jLabel7.setText("rata rata");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 230, 70, 16);
        getContentPane().add(txtHasil);
        txtHasil.setBounds(141, 232, 250, 20);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        StudentRecord student = new StudentRecord();
        student.setName(txtNama.getText());
        student.setAddress(txtAlamat.getText());
        student.setAge(Integer.parseInt(txtUmur.getText()));
        student.setmathGrade(Double.parseDouble(txtMatematika.getText()));
        student.setEnglishGrade(Double.parseDouble(txtBing.getText()));
        student.setScienceGrade(Double.parseDouble(txtIlmuPengetahuan.getText()));
        txtHasil.setText(String.valueOf(student.getAverage()));
        
        
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBing;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtIlmuPengetahuan;
    private javax.swing.JTextField txtMatematika;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUmur;
    // End of variables declaration//GEN-END:variables
}
